// Luxury Car Inventory - 10 per brand, 2022-2026 editions
const cars = [
  // ===== JAGUAR (10 models) =====
  {
    id: 'jaguar-f-type-2026',
    brand: 'Jaguar',
    model: 'F-Type R75',
    year: 2026,
    price: 115000,
    currency: 'NGN',
    engine: '5.0L V8 Supercharged',
    horsepower: 575,
    torque: '516 lb-ft',
    acceleration: '3.5s',
    topSpeed: '186 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'British Racing Green',
    interior: 'Windsor Leather',
    mileage: 0,
    condition: 'New',
    stock: 3,
    description: 'The final edition of the legendary F-Type, celebrating 75 years of Jaguar sports cars. A masterpiece of British engineering.',
    features: ['Adaptive Dynamics', 'Active Exhaust', 'Meridian Sound System', 'Heated Seats', 'Navigation Pro', 'Apple CarPlay', 'Android Auto', '360° Camera'],
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-f-type-2025',
    brand: 'Jaguar',
    model: 'F-Type P450',
    year: 2025,
    price: 86000,
    currency: 'NGN',
    engine: '5.0L V8 Supercharged',
    horsepower: 450,
    torque: '428 lb-ft',
    acceleration: '4.4s',
    topSpeed: '177 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'RWD',
    color: 'Santorini Black',
    interior: 'Ebony Leather',
    mileage: 0,
    condition: 'New',
    stock: 5,
    description: 'Pure driving exhilaration with the iconic V8 soundtrack. The F-Type P450 delivers authentic sports car performance.',
    features: ['Sport Suspension', 'LED Headlights', 'Touch Pro Duo', 'Climate Seats', 'Blind Spot Monitor', 'Lane Keep Assist'],
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c6c807?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-i-pace-2026',
    brand: 'Jaguar',
    model: 'I-PACE EV400',
    year: 2026,
    price: 74000,
    currency: 'NGN',
    engine: 'Dual Electric Motors',
    horsepower: 394,
    torque: '512 lb-ft',
    acceleration: '4.5s',
    topSpeed: '124 mph',
    transmission: 'Single-speed',
    drivetrain: 'AWD',
    color: 'Farallon Pearl Black',
    interior: 'Oyster Leather',
    mileage: 0,
    condition: 'New',
    stock: 4,
    range: '292 miles',
    description: 'The award-winning all-electric performance SUV. Zero emissions, maximum Jaguar.',
    features: ['Fast Charging', 'Air Suspension', 'Meridian 3D Sound', 'Panoramic Roof', 'Wireless Charging', 'Head-up Display'],
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-i-pace-2024',
    brand: 'Jaguar',
    model: 'I-PACE Black',
    year: 2024,
    price: 78000,
    currency: 'NGN',
    engine: 'Dual Electric Motors',
    horsepower: 394,
    torque: '512 lb-ft',
    acceleration: '4.5s',
    topSpeed: '124 mph',
    transmission: 'Single-speed',
    drivetrain: 'AWD',
    color: 'Narvik Black',
    interior: 'Ebony Leather with Red Stitching',
    mileage: 1200,
    condition: 'Certified Pre-Owned',
    stock: 2,
    range: '292 miles',
    description: 'The stealthy Black edition of Jaguar\'s electric performance SUV with exclusive design elements.',
    features: ['Black Exterior Pack', '22" Black Wheels', 'Red Brake Calipers', 'Adaptive Cruise', '360° Parking Aid'],
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-xe-2025',
    brand: 'Jaguar',
    model: 'XE R-Dynamic SE',
    year: 2025,
    price: 52000,
    currency: 'NGN',
    engine: '2.0L Turbocharged 4-cylinder',
    horsepower: 296,
    torque: '295 lb-ft',
    acceleration: '5.4s',
    topSpeed: '155 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Eiger Grey',
    interior: 'Taurus Leather',
    mileage: 0,
    condition: 'New',
    stock: 6,
    description: 'The compact executive sedan with sports car DNA. Agile, responsive, and unmistakably Jaguar.',
    features: ['R-Dynamic Styling', '12-way Power Seats', 'Interactive Driver Display', 'Clear Exit Monitor'],
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-xf-2026',
    brand: 'Jaguar',
    model: 'XF R-Dynamic HSE',
    year: 2026,
    price: 68000,
    currency: 'NGN',
    engine: '2.0L Turbocharged 4-cylinder',
    horsepower: 296,
    torque: '295 lb-ft',
    acceleration: '5.8s',
    topSpeed: '155 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Portofino Blue',
    interior: 'Light Oyster Leather',
    mileage: 0,
    condition: 'New',
    stock: 4,
    description: 'The executive sedan redefined. Luxury meets technology in the most advanced XF ever built.',
    features: ['Pivi Pro Infotainment', 'Active Road Noise Cancellation', 'Wireless Device Charging', 'PM2.5 Cabin Filtration'],
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-e-pace-2025',
    brand: 'Jaguar',
    model: 'E-PACE R-Dynamic',
    year: 2025,
    price: 54000,
    currency: 'NGN',
    engine: '2.0L Turbocharged 4-cylinder',
    horsepower: 246,
    torque: '269 lb-ft',
    acceleration: '7.0s',
    topSpeed: '143 mph',
    transmission: '9-speed Automatic',
    drivetrain: 'AWD',
    color: 'Fuji White',
    interior: 'Ebony/Ebony Leather',
    mileage: 0,
    condition: 'New',
    stock: 5,
    description: 'The compact performance SUV with sports car attitude. Everyday practicality meets Jaguar excitement.',
    features: ['Configurable Dynamics', '11.4" Touchscreen', '3D Surround Camera', 'Traffic Sign Recognition'],
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-f-pace-2026',
    brand: 'Jaguar',
    model: 'F-PACE SVR',
    year: 2026,
    price: 92000,
    currency: 'NGN',
    engine: '5.0L V8 Supercharged',
    horsepower: 550,
    torque: '516 lb-ft',
    acceleration: '3.8s',
    topSpeed: '178 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Atacama Orange',
    interior: 'Semi-aniline Leather',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The ultimate performance SUV. Supercharged V8 power meets everyday versatility.',
    features: ['SVR Tuned Suspension', 'Active Exhaust', '22" Forged Wheels', 'SVR Performance Seats', 'Adaptive Dynamics'],
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-f-pace-2023',
    brand: 'Jaguar',
    model: 'F-PACE P400e',
    year: 2023,
    price: 66000,
    currency: 'NGN',
    engine: '2.0L Plug-in Hybrid',
    horsepower: 398,
    torque: '472 lb-ft',
    acceleration: '5.0s',
    topSpeed: '149 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Eiger Grey',
    interior: 'Windsor Leather',
    mileage: 8500,
    condition: 'Certified Pre-Owned',
    stock: 1,
    range: '33 miles electric',
    description: 'Plug-in hybrid efficiency with Jaguar performance. The best of both worlds.',
    features: ['Plug-in Hybrid', 'Rapid Charging', 'Cabin Air Ionisation', 'Activity Key', 'Adaptive Cruise Control'],
    image: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=800&h=600&fit=crop'
  },
  {
    id: 'jaguar-xe-2022',
    brand: 'Jaguar',
    model: 'XE R-Dynamic Black',
    year: 2022,
    price: 45000,
    currency: 'NGN',
    engine: '2.0L Turbocharged 4-cylinder',
    horsepower: 296,
    torque: '295 lb-ft',
    acceleration: '5.4s',
    topSpeed: '155 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Santorini Black',
    interior: 'Ebony Leather with Red Stitching',
    mileage: 15000,
    condition: 'Certified Pre-Owned',
    stock: 1,
    description: 'The stealth edition of the XE sports sedan. All-black styling with dynamic performance.',
    features: ['Black Pack', '19" Black Wheels', 'Privacy Glass', 'Heated Steering Wheel', 'Keyless Entry'],
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=600&fit=crop'
  },

  // ===== LAMBORGHINI (10 models) =====
  {
    id: 'lamborghini-revuelto-2026',
    brand: 'Lamborghini',
    model: 'Revuelto',
    year: 2026,
    price: 608000,
    currency: 'NGN',
    engine: '6.5L V12 Hybrid',
    horsepower: 1001,
    torque: '815 lb-ft',
    acceleration: '2.5s',
    topSpeed: '217 mph',
    transmission: '8-speed DCT',
    drivetrain: 'AWD',
    color: 'Arancio Xanto',
    interior: 'Nero Ade Leather',
    mileage: 0,
    condition: 'New',
    stock: 1,
    description: 'The first V12 hybrid super sports car. A new era of Lamborghini begins with 1001 horsepower of pure fury.',
    features: ['Hybrid Powertrain', 'Carbon Fiber Monocoque', 'Active Aerodynamics', 'Drive Mode Selector', 'Carbon Ceramic Brakes'],
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-revuelto-2025',
    brand: 'Lamborghini',
    model: 'Revuelto Roadster',
    year: 2025,
    price: 675000,
    currency: 'NGN',
    engine: '6.5L V12 Hybrid',
    horsepower: 1001,
    torque: '815 lb-ft',
    acceleration: '2.6s',
    topSpeed: '217 mph',
    transmission: '8-speed DCT',
    drivetrain: 'AWD',
    color: 'Verde Mantis',
    interior: 'Nero Cosmus/Verde Faunus',
    mileage: 0,
    condition: 'New',
    stock: 1,
    description: 'Open-top V12 hybrid exhilaration. Feel the wind with 1001 horsepower at your command.',
    features: ['Removable Roof Panels', 'Hybrid System', 'All-Wheel Drive', 'Rear-Wheel Steering', 'Magnetorheological Dampers'],
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-huracan-2024',
    brand: 'Lamborghini',
    model: 'Huracán Tecnica',
    year: 2024,
    price: 282000,
    currency: 'NGN',
    engine: '5.2L V10',
    horsepower: 631,
    torque: '417 lb-ft',
    acceleration: '3.2s',
    topSpeed: '202 mph',
    transmission: '7-speed DCT',
    drivetrain: 'RWD',
    color: 'Grigio Telesto',
    interior: 'Nero Ade with Rosso Alala',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The ultimate road-going Huracán. Track-bred technology for the street.',
    features: ['LDVI System', 'Carbon Ceramic Brakes', 'Rear-Wheel Steering', 'Torque Vectoring', 'Sport Seats'],
    image: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-huracan-2023',
    brand: 'Lamborghini',
    model: 'Huracán STO',
    year: 2023,
    price: 335000,
    currency: 'NGN',
    engine: '5.2L V10',
    horsepower: 631,
    torque: '417 lb-ft',
    acceleration: '3.0s',
    topSpeed: '193 mph',
    transmission: '7-speed DCT',
    drivetrain: 'RWD',
    color: 'Blu Laufey',
    interior: 'Carbon Fiber/Alcantara',
    mileage: 2100,
    condition: 'Certified Pre-Owned',
    stock: 1,
    description: 'A road-legal race car. The most track-focused Huracán ever built.',
    features: ['Full Carbon Body', 'Racing Bucket Seats', 'Roll Cage', 'Fire Extinguisher', 'Track Telemetry'],
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-huracan-2022',
    brand: 'Lamborghini',
    model: 'Huracán EVO RWD',
    year: 2022,
    price: 248000,
    currency: 'NGN',
    engine: '5.2L V10',
    horsepower: 602,
    torque: '413 lb-ft',
    acceleration: '3.3s',
    topSpeed: '202 mph',
    transmission: '7-speed DCT',
    drivetrain: 'RWD',
    color: 'Giallo Inti',
    interior: 'Nero Ade Leather',
    mileage: 4500,
    condition: 'Certified Pre-Owned',
    stock: 1,
    description: 'Pure rear-wheel drive excitement. The most engaging Huracán for purists.',
    features: ['Performance Traction Control', 'Magnetorheological Suspension', 'Dynamic Steering', 'Apple CarPlay'],
    image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-urus-2026',
    brand: 'Lamborghini',
    model: 'Urus SE',
    year: 2026,
    price: 265000,
    currency: 'NGN',
    engine: '4.0L V8 Twin-Turbo Hybrid',
    horsepower: 789,
    torque: '738 lb-ft',
    acceleration: '3.4s',
    topSpeed: '194 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Nero Noctis',
    interior: 'Q-Citura Leather',
    mileage: 0,
    condition: 'New',
    stock: 3,
    description: 'The first hybrid Super SUV. Electrified power meets Lamborghini DNA.',
    features: ['Plug-in Hybrid', 'Adaptive Air Suspension', 'Active Roll Stabilization', 'Rear-Wheel Steering', 'ANIMA Drive Modes'],
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-urus-2025',
    brand: 'Lamborghini',
    model: 'Urus Performante',
    year: 2025,
    price: 268000,
    currency: 'NGN',
    engine: '4.0L V8 Twin-Turbo',
    horsepower: 657,
    torque: '627 lb-ft',
    acceleration: '3.3s',
    topSpeed: '190 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Verde Mantis',
    interior: 'Black Alcantara with Contrast Stitching',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The most powerful Urus ever. Lighter, faster, meaner.',
    features: ['Carbon Fiber Parts', 'Steel Springs', 'Akrapovič Exhaust', 'Forged Wheels', 'Sport Bucket Seats'],
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c6c807?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-urus-2024',
    brand: 'Lamborghini',
    model: 'Urus S',
    year: 2024,
    price: 235000,
    currency: 'NGN',
    engine: '4.0L V8 Twin-Turbo',
    horsepower: 657,
    torque: '627 lb-ft',
    acceleration: '3.5s',
    topSpeed: '190 mph',
    transmission: '8-speed Automatic',
    drivetrain: 'AWD',
    color: 'Bianco Monocerus',
    interior: 'Leather with Q-Citura',
    mileage: 3200,
    condition: 'Certified Pre-Owned',
    stock: 1,
    description: 'The Super SUV refined. Enhanced design and increased power.',
    features: ['Updated Styling', 'Adaptive Air Suspension', 'B&O Sound System', 'Night Vision', '360° Camera'],
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-countach-2022',
    brand: 'Lamborghini',
    model: 'Countach LPI 800-4',
    year: 2022,
    price: 2640000,
    currency: 'NGN',
    engine: '6.5L V12 Hybrid',
    horsepower: 803,
    torque: '557 lb-ft',
    acceleration: '2.8s',
    topSpeed: '221 mph',
    transmission: '7-speed ISR',
    drivetrain: 'AWD',
    color: 'Giallo Countach',
    interior: 'Red Leather with Carbon',
    mileage: 150,
    condition: 'Collector',
    stock: 1,
    description: 'The legendary icon reborn. Limited to 112 units worldwide. A piece of automotive history.',
    features: ['Limited Edition', 'Carbon Fiber Body', 'Scissor Doors', 'Hybrid System', 'Forged Wheels'],
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&h=600&fit=crop'
  },
  {
    id: 'lamborghini-aventador-2022',
    brand: 'Lamborghini',
    model: 'Aventador LP 780-4 Ultimae',
    year: 2022,
    price: 546000,
    currency: 'NGN',
    engine: '6.5L V12',
    horsepower: 769,
    torque: '531 lb-ft',
    acceleration: '2.8s',
    topSpeed: '221 mph',
    transmission: '7-speed ISR',
    drivetrain: 'AWD',
    color: 'Grigio Acheso',
    interior: 'Nero Ade/Grigio Octans',
    mileage: 800,
    condition: 'Collector',
    stock: 1,
    description: 'The final Aventador. The purest, most powerful naturally aspirated V12 ever. The end of an era.',
    features: ['Final Edition', 'Carbon Ceramic Brakes', 'LDVA System', 'Active Aerodynamics', 'Forged Leirion Wheels'],
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop'
  },

  // ===== FERRARI (10 models) =====
  {
    id: 'ferrari-sf90-2026',
    brand: 'Ferrari',
    model: 'SF90 XX Stradale',
    year: 2026,
    price: 840000,
    currency: 'NGN',
    engine: '4.0L V8 Twin-Turbo Hybrid',
    horsepower: 1016,
    torque: '593 lb-ft',
    acceleration: '2.3s',
    topSpeed: '199 mph',
    transmission: '8-speed DCT',
    drivetrain: 'AWD',
    color: 'Rosso Corsa',
    interior: 'Alcantara with Carbon Fiber',
    mileage: 0,
    condition: 'New',
    stock: 1,
    description: 'The first road-legal XX car. Extreme track performance unleashed on the road. Limited to 799 units.',
    features: ['Hybrid Powertrain', 'Fixed Rear Wing', 'Lightweight Components', 'Track Telemetry', 'Racing Bucket Seats'],
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-sf90-2025',
    brand: 'Ferrari',
    model: 'SF90 Stradale',
    year: 2025,
    price: 625000,
    currency: 'NGN',
    engine: '4.0L V8 Twin-Turbo Hybrid',
    horsepower: 986,
    torque: '590 lb-ft',
    acceleration: '2.5s',
    topSpeed: '211 mph',
    transmission: '8-speed DCT',
    drivetrain: 'AWD',
    color: 'Giallo Modena',
    interior: 'Nero Leather with Yellow Stitching',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The most powerful Ferrari ever. Plug-in hybrid technology delivering unprecedented performance.',
    features: ['986 HP Hybrid', 'Electric AWD', 'eManettino', 'Carbon Fiber Wheels', 'Magnetorheological Dampers'],
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-296-2026',
    brand: 'Ferrari',
    model: '296 GTB',
    year: 2026,
    price: 342000,
    currency: 'NGN',
    engine: '3.0L V6 Twin-Turbo Hybrid',
    horsepower: 819,
    torque: '546 lb-ft',
    acceleration: '2.9s',
    topSpeed: '205 mph',
    transmission: '8-speed DCT',
    drivetrain: 'RWD',
    color: 'Rosso Corsa',
    interior: 'Nero/Charcoal Leather',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The first V6 hybrid Ferrari. A new era of mid-rear engine sports cars begins.',
    features: ['V6 Hybrid', 'Assetto Fiorano Package', 'Active Rear Spoiler', 'Carbon Ceramic Brakes', 'eManettino'],
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-296-2025',
    brand: 'Ferrari',
    model: '296 GTS',
    year: 2025,
    price: 360000,
    currency: 'NGN',
    engine: '3.0L V6 Twin-Turbo Hybrid',
    horsepower: 819,
    torque: '546 lb-ft',
    acceleration: '2.9s',
    topSpeed: '205 mph',
    transmission: '8-speed DCT',
    drivetrain: 'RWD',
    color: 'Blu Tour de France',
    interior: 'Cuoio Leather',
    mileage: 0,
    condition: 'New',
    stock: 1,
    description: 'Open-top V6 hybrid exhilaration. The wind in your hair and 819 horsepower at your feet.',
    features: ['Retractable Hardtop', 'Hybrid System', 'Active Suspension', 'Premium Audio', 'Launch Control'],
    image: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-f8-2023',
    brand: 'Ferrari',
    model: 'F8 Tributo',
    year: 2023,
    price: 324000,
    currency: 'NGN',
    engine: '3.9L V8 Twin-Turbo',
    horsepower: 710,
    torque: '568 lb-ft',
    acceleration: '2.9s',
    topSpeed: '211 mph',
    transmission: '7-speed DCT',
    drivetrain: 'RWD',
    color: 'Rosso Corsa',
    interior: 'Nero Leather with Red Stitching',
    mileage: 1800,
    condition: 'Certified Pre-Owned',
    stock: 1,
    description: 'A tribute to the most powerful V8 in Ferrari history. Pure, unadulterated performance.',
    features: ['710 HP V8', 'Ferrari Dynamic Enhancer', 'Carbon Fiber Interior', 'Sport Exhaust', 'Telemetry System'],
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-f8-2022',
    brand: 'Ferrari',
    model: 'F8 Spider',
    year: 2022,
    price: 302000,
    currency: 'NGN',
    engine: '3.9L V8 Twin-Turbo',
    horsepower: 710,
    torque: '568 lb-ft',
    acceleration: '2.9s',
    topSpeed: '211 mph',
    transmission: '7-speed DCT',
    drivetrain: 'RWD',
    color: 'Grigio Silverstone',
    interior: 'Cuoio Leather',
    mileage: 3500,
    condition: 'Certified Pre-Owned',
    stock: 1,
    description: 'Open-top V8 thrills. The most powerful production convertible Ferrari ever.',
    features: ['Retractable Hardtop', 'Adaptive Suspension', 'Carbon Ceramic Brakes', 'Premium Hifi', 'Front Lift System'],
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-roma-2026',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2026,
    price: 243000,
    currency: 'NGN',
    engine: '3.9L V8 Twin-Turbo',
    horsepower: 611,
    torque: '561 lb-ft',
    acceleration: '3.4s',
    topSpeed: '199 mph',
    transmission: '8-speed DCT',
    drivetrain: 'RWD',
    color: 'Bianco Avus',
    interior: 'Tortora Leather',
    mileage: 0,
    condition: 'New',
    stock: 3,
    description: 'La Nuova Dolce Vita. Elegant, timeless design meets Ferrari performance in the 21st century GT.',
    features: ['Elegant Design', '8-speed DCT', 'Matrix LED Headlights', '16" Digital Cockpit', 'Premium Audio'],
    image: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-roma-2024',
    brand: 'Ferrari',
    model: 'Roma Spider',
    year: 2024,
    price: 280000,
    currency: 'NGN',
    engine: '3.9L V8 Twin-Turbo',
    horsepower: 611,
    torque: '561 lb-ft',
    acceleration: '3.4s',
    topSpeed: '199 mph',
    transmission: '8-speed DCT',
    drivetrain: 'RWD',
    color: 'Blu Abu Dhabi',
    interior: 'Cuoio Leather',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The soft-top Ferrari Roma. Timeless elegance meets open-air exhilaration.',
    features: ['Soft Top Roof', 'Adaptive Headlights', 'Wireless Charging', 'Apple CarPlay', 'Magnesium Gearshift Paddles'],
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-purosangue-2026',
    brand: 'Ferrari',
    model: 'Purosangue',
    year: 2026,
    price: 393000,
    currency: 'NGN',
    engine: '6.5L V12',
    horsepower: 715,
    torque: '528 lb-ft',
    acceleration: '3.3s',
    topSpeed: '193 mph',
    transmission: '8-speed DCT',
    drivetrain: 'AWD',
    color: 'Rosso Corsa',
    interior: 'Burmester Premium Audio',
    mileage: 0,
    condition: 'New',
    stock: 2,
    description: 'The first four-door Ferrari. A revolutionary concept that redefines the Prancing Horse\'s DNA.',
    features: ['V12 Power', 'Suicide Doors', 'Active Suspension', 'Carbon Ceramic Brakes', 'Burmester 3D Sound'],
    image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop'
  },
  {
    id: 'ferrari-daytona-2023',
    brand: 'Ferrari',
    model: 'Daytona SP3',
    year: 2023,
    price: 2250000,
    currency: 'NGN',
    engine: '6.5L V12',
    horsepower: 829,
    torque: '514 lb-ft',
    acceleration: '2.85s',
    topSpeed: '211 mph',
    transmission: '7-speed DCT',
    drivetrain: 'RWD',
    color: 'Rosso Magma',
    interior: 'Nero with Red Accents',
    mileage: 300,
    condition: 'Collector',
    stock: 1,
    description: 'The Icona series masterpiece. Limited to 599 units. A tribute to Ferrari\'s racing heritage.',
    features: ['Limited Edition', 'Carbon Fiber Body', 'Targa Roof', '829 HP V12', 'Center-Lock Wheels'],
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop'
  }
];

module.exports = cars;
